# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resource_inclusion}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John-Mason P. Shackelford"]
  s.date = %q{2011-01-11}
  s.description = %q{Resource Inclusion allows one to specify once per controller associated resources to be included when a resource is serialized.}
  s.email = %q{jpshack@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/resource_inclusion.rb",
    "lib/resource_inclusion/class_methods.rb",
    "lib/resource_inclusion/instance_methods.rb",
    "lib/resource_inclusion/resource_include_responder.rb",
    "lib/resource_inclusion/resource_inclusion.rb",
    "lib/resource_inclusion/version.rb",
    "resource_inclusion.gemspec",
    "test/app/Gemfile",
    "test/app/Gemfile.lock",
    "test/app/Rakefile",
    "test/app/app/controllers/application_controller.rb",
    "test/app/app/controllers/comments_controller.rb",
    "test/app/app/models/comment.rb",
    "test/app/app/models/user.rb",
    "test/app/config.ru",
    "test/app/config/application.rb",
    "test/app/config/boot.rb",
    "test/app/config/database.yml",
    "test/app/config/environment.rb",
    "test/app/config/environments/test.rb",
    "test/app/config/routes.rb",
    "test/app/db/development.sqlite3",
    "test/app/db/migrate/20110111090943_initial_test.rb",
    "test/app/db/test.sqlite3",
    "test/app/log/development.log",
    "test/app/log/test.log",
    "test/app/spec/controllers/comments_controller_spec.rb",
    "test/app/spec/spec_helper.rb",
    "test/app/spec/support/xpath_matcher.rb"
  ]
  s.homepage = %q{http://github.com/jpshackelford/resource_inclusion}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A handy macro for including associated models in your REST APIs.}
  s.test_files = [
    "test/app/app/controllers/application_controller.rb",
    "test/app/app/controllers/comments_controller.rb",
    "test/app/app/models/comment.rb",
    "test/app/app/models/user.rb",
    "test/app/config/application.rb",
    "test/app/config/boot.rb",
    "test/app/config/environment.rb",
    "test/app/config/environments/test.rb",
    "test/app/config/routes.rb",
    "test/app/db/migrate/20110111090943_initial_test.rb",
    "test/app/spec/controllers/comments_controller_spec.rb",
    "test/app/spec/spec_helper.rb",
    "test/app/spec/support/xpath_matcher.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.1"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.1"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.1"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

